#!/bin/sh -ex

pwd
if [ -z "$MAKE" ]; then
	MAKE=make
fi
cmd=$1
shift
case "$cmd" in
  build-exclude-list|dist-exclude-list|prepare-dist)
    ;;
  bootstrap)
    ./autogen.sh
    # fix old and broken libtools, which can't recognise 64 bit windows libs and dlls.
    find -name libtool -o -name ltmain.sh | xargs sed -i -e "s,'file format pe-i386.*\?','file format \(pei\*-i386\(\.\*architecture: i386\)\?|pe-arm-wince|pe-x86-64\)'," -e 's,cmd \/\/c,,'
    ;;
  configure)
    if [ "$ZBS_BUILDER_TYPE" != "mingw" ]; then
      echo "ZWA local compilation not needed on this platform, using the system's gettext."
      exit 0
	else
		OPTS="--with-included-gettext --disable-csharp --disable-rpath --disable-libasprintf --disable-static --enable-threads=posix"
    fi
	set -x
	(cd gettext-runtime && ./configure $@ $OPTS)
    ;;
  make)
    if [ "$ZBS_BUILDER_TYPE" != "mingw" ]; then
      echo "ZWA local compilation not needed on this platform, using the system's gettext."
      exit 0
    fi
	(cd gettext-runtime/intl && $MAKE $@)
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

#vim: ts=2 sw=2 expandtab
